# Docker compose for build pipeline

services:
  mock-data-recipient:
    container_name: mock-data-recipient
    image: mock-data-recipient
    hostname: mock-data-recipient
    ports: 
      - "9001:9001"
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    # FIXME - MJS - commented out volumes below as volume is mounted as 1001:121 (vsts:docker) in build pipeline and causes issue with chown in dockerfile (appuser:appgroup), ie stops container from starting because of different user      
    # volumes:
    #   - "./_temp/mock-data-recipient/tmp:/tmp"      
    healthcheck:
      test: wget --no-check-certificate --no-verbose --spider https://localhost:9001/health || exit 1
      timeout: 5s
      interval: 5s
      retries: 50
    depends_on:
      mssql:
        condition: service_healthy

  mock-data-recipient-unit-tests:
    container_name: mock-data-recipient-unit-tests
    image: mock-data-recipient-unit-tests
    build:
      context: ..
      dockerfile: Dockerfile.unit-tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - "./_temp/mock-data-recipient-unit-tests/testresults:/testresults"
    depends_on:
      mssql:
        condition: service_healthy
      mock-data-recipient:
        condition: service_healthy        

  mssql:
    container_name: sql1
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" -No || exit 1 
      timeout: 5s
      interval: 5s
      retries: 20    
