# Docker compose base file for E2E and integration tests.
# This compose file is extended by docker-compose.E2ETests.yml and docker-compose.IntegrationTests.yml files to compose up and execute E2E or integration tests the Mock Data Recipient.

version: '3.8'

services:
  mock-register:
    container_name: mock-register
    image: mock-register
    hostname: mock-register
    ports: 
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7006:7006"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release  
    healthcheck:
      test: ((wget --no-check-certificate --no-verbose --spider https://localhost:7006/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:7002/idp/.well-known/openid-configuration)) || exit 1
      timeout: 15s
      interval: 15s
      retries: 20
    depends_on:
      mssql:
        condition: service_healthy

  mock-data-holder:
    container_name: mock-data-holder
    image: mock-data-holder
    hostname: mock-data-holder
    ports: 
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8005:8005"
      - "3000:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - CdrAuthServer__AccessTokenExpirySeconds=3600
      - CdrAuthServer__SupportJarmEncryption=true
    healthcheck:
      test: ((wget --no-check-certificate --no-verbose --spider https://localhost:8005/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:8001/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:3000)) || exit 1      
      timeout: 15s
      interval: 15s
      retries: 20 
    depends_on:
      mock-register:
        condition: service_healthy        

  mock-data-holder-energy:
    container_name: mock-data-holder-energy
    image: mock-data-holder-energy
    hostname: mock-data-holder-energy
    ports: 
      - "8100:8100"
      - "8101:8101"
      - "8102:8102"
      - "8105:8105"
      - "3100:3100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - CdrAuthServer__AccessTokenExpirySeconds=3600
    healthcheck:
      test: ((wget --no-check-certificate --no-verbose --spider https://localhost:8105/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:8101/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:3100)) || exit 1      
      timeout: 15s
      interval: 15s
      retries: 20
    depends_on:
      mock-data-holder:
        condition: service_healthy       

  mock-data-recipient:
    container_name: mock-data-recipient
    image: mock-data-recipient
    hostname: mock-data-recipient
    ports: 
      - "9001:9001"
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    healthcheck:
      test: wget --no-check-certificate --no-verbose --spider https://localhost:9001/health || exit 1
      timeout: 15s
      interval: 15s
      retries: 20
    depends_on:
      mock-data-holder-energy:
        condition: service_healthy
      
  mssql:
    container_name: sql1
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" || exit 1 
      timeout: 5s
      interval: 15s
      retries: 20    
