# Dockerfile for E2E tests

# NB: Ensure playwright version used in CDR.DataRecipient.E2ETests and base image below are same (ie currently 1.43.0)
FROM mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy AS build

###############################################################################
# Build E2E tests
###############################################################################
WORKDIR /src

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# Build tests
WORKDIR /src/CDR.DataRecipient.E2ETests
RUN dotnet build --configuration Release

###############################################################################
# Run E2E tests
###############################################################################
ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "--results-directory", "/testresults"]
# ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--filter", "AC04_DynamicClientRegistration", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "-r", "/testresults"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]
