# Dockerfile for running unit tests

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install ca certificate
RUN apt-get update && apt-get install -y sudo
RUN sudo cp ./CDR.DataRecipient.Web/Certificates/ca.crt /usr/local/share/ca-certificates/ca.crt
RUN sudo update-ca-certificates

# Build tests
WORKDIR /src
RUN dotnet build --configuration Release

RUN dotnet tool install --global PowerShell
ENV PATH="$PATH:/root/.dotnet/tools"
RUN pwsh CDR.DataRecipient.E2ETests/bin/Release/net10.0/playwright.ps1 install --with-deps chromium

# Run tests
ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--no-launch-profile", "--report-trx", "--results-directory", "/testresults"]
